import {
  DBCourse,
  DBEnrollment,
  DBCertificate,
  DBWatchlistItem,
  DBNotification,
  DBSubscriptionPlan,
} from "@/types/database";

export const MOCK_COURSES: DBCourse[] = [
  {
    id: "course-1",
    slug: "market-foundations",
    title: "Market Foundations & Structure",
    level: "LEVEL 01",
    levelNumber: 1,
    category: "Foundations",
    tagline: "The Architecture of Capital Markets",
    description:
      "Demystify how stock exchanges operate, how orders match, and how to read institutional price discovery without speculation.",
    durationHours: 8,
    lessonsCount: 12,
    modulesCount: 3,
    prerequisites: ["None — Designed for Absolute Beginners"],
    skillsLearned: ["Order Book Mechanics", "Bid/Ask Spreads", "Depository Structures", "Broker Models"],
    thumbnailUrl: "/courses/level-01.jpg",
    instructor: {
      name: "Aditya Verma",
      title: "Senior Market Educator",
      avatar: "AV",
    },
    modules: [
      {
        id: "mod-1-1",
        courseId: "course-1",
        order: 1,
        title: "Exchange Architecture & Clearing",
        durationMinutes: 120,
        lessons: [
          {
            id: "les-1-1-1",
            moduleId: "mod-1-1",
            courseId: "course-1",
            order: 1,
            title: "How Indian Exchanges (NSE & BSE) Function",
            durationMinutes: 35,
            type: "video",
            contentSummary:
              "An institutional look into electronic order matching, trade clearing through NSCCL, and depository operations at CDSL & NSDL.",
            notesMarkdown:
              "### Core Takeaways\n- NSE and BSE are regulated secondary market trading venues.\n- Order matching follows price-time priority.\n- Depositories (CDSL/NSDL) hold dematerialized securities electronically.",
            keyTakeaways: ["Price-time priority matching", "Clearing corporation guarantees", "T+1 settlement mechanics"],
          },
          {
            id: "les-1-1-2",
            moduleId: "mod-1-1",
            courseId: "course-1",
            order: 2,
            title: "Order Types: Market, Limit, and Stop Orders",
            durationMinutes: 45,
            type: "interactive_case",
            contentSummary: "Comparing aggressive market orders vs. passive limit orders. Understanding slippage in volatile sessions.",
            keyTakeaways: ["Limit orders preserve execution price", "Market orders pay the bid-ask spread", "Stop-loss trigger mechanics"],
          },
        ],
      },
      {
        id: "mod-1-2",
        courseId: "course-1",
        order: 2,
        title: "Financial Instruments & Equities",
        durationMinutes: 150,
        lessons: [
          {
            id: "les-1-2-1",
            moduleId: "mod-1-2",
            courseId: "course-1",
            order: 1,
            title: "Understanding Share Capital & Dividend Yields",
            durationMinutes: 40,
            type: "video",
            contentSummary: "What owning equity actually means: voting rights, capital appreciation, and corporate dividend distribution.",
            keyTakeaways: ["Equity represents fractional corporate ownership", "Dividend yield = Annual dividend / Current share price"],
          },
        ],
      },
    ],
  },
  {
    id: "course-2",
    slug: "technical-analysis-foundations",
    title: "Technical Analysis Foundations",
    level: "LEVEL 02",
    levelNumber: 2,
    category: "Technical",
    tagline: "Price Action & Structural Trends",
    description:
      "Understand multi-timeframe chart architecture, support & resistance confluence, moving average smoothing, and volume validation.",
    durationHours: 10,
    lessonsCount: 16,
    modulesCount: 4,
    prerequisites: ["Level 01: Market Foundations"],
    skillsLearned: ["Support & Resistance", "Moving Averages (SMA/EMA)", "Volume Profile", "Trend Identification"],
    thumbnailUrl: "/courses/level-02.jpg",
    instructor: {
      name: "Siddharth Sen",
      title: "Technical Market Strategist",
      avatar: "SS",
    },
    modules: [
      {
        id: "mod-2-1",
        courseId: "course-2",
        order: 1,
        title: "Price Action & Market Geometry",
        durationMinutes: 140,
        lessons: [
          {
            id: "les-2-1-1",
            moduleId: "mod-2-1",
            courseId: "course-2",
            order: 1,
            title: "Understanding Support & Resistance Confluence",
            durationMinutes: 45,
            type: "video",
            contentSummary:
              "How institutional orders create price memory. Identifying historical flip zones where previous resistance converts into support.",
            notesMarkdown:
              "### Support and Resistance Rules\n1. Support is a price area where demand overcomes selling pressure.\n2. When broken with heavy volume, support becomes future resistance.\n3. The more times a level is tested, the more orders are absorbed.",
            keyTakeaways: ["Price memory flip zones", "Volume confirmation on test", "Avoid trading in the middle of a range"],
          },
          {
            id: "les-2-1-2",
            moduleId: "mod-2-1",
            courseId: "course-2",
            order: 2,
            title: "Moving Averages: 20, 50, and 200 EMAs",
            durationMinutes: 40,
            type: "interactive_case",
            contentSummary: "Using moving averages as dynamic trailing support and baseline filters rather than magical crystal balls.",
            keyTakeaways: ["20 EMA for short-term momentum", "50 EMA for medium institutional trend", "200 EMA for macro regime filter"],
          },
        ],
      },
    ],
  },
  {
    id: "course-3",
    slug: "fundamental-valuation",
    title: "Fundamental Analysis & Valuation",
    level: "LEVEL 03",
    levelNumber: 3,
    category: "Fundamental",
    tagline: "Financial Statements & Valuation Multiples",
    description:
      "Learn how to audit balance sheets, cash flows, ROCE, and management capital allocation to uncover durable economic moats.",
    durationHours: 12,
    lessonsCount: 18,
    modulesCount: 4,
    prerequisites: ["Level 01: Market Foundations"],
    skillsLearned: ["P&L and Balance Sheet Analysis", "Cash Flow Interrogation", "ROCE & ROE", "P/E vs Growth"],
    thumbnailUrl: "/courses/level-03.jpg",
    instructor: {
      name: "Dr. Meera Nambiar",
      title: "Fundamental Equity Research Fellow",
      avatar: "MN",
    },
    modules: [
      {
        id: "mod-3-1",
        courseId: "course-3",
        order: 1,
        title: "Dissecting Financial Statements",
        durationMinutes: 160,
        lessons: [
          {
            id: "les-3-1-1",
            moduleId: "mod-3-1",
            courseId: "course-3",
            order: 1,
            title: "Operating Cash Flow vs. Net Profit",
            durationMinutes: 50,
            type: "video",
            contentSummary: "Why earnings can be manipulated through accruals while cash flows tell the unvarnished corporate reality.",
            keyTakeaways: ["Operating Cash Flow / EBITDA ratio", "Working capital traps", "Free Cash Flow generation"],
          },
        ],
      },
    ],
  },
  {
    id: "course-4",
    slug: "portfolio-construction",
    title: "Portfolio Construction & Risk Budgeting",
    level: "LEVEL 04",
    levelNumber: 4,
    category: "Portfolio",
    tagline: "Asset Allocation & Drawdown Management",
    description:
      "Design resilient multi-asset equity allocations, position sizing rules, and maximum allowable drawdown constraints.",
    durationHours: 8,
    lessonsCount: 14,
    modulesCount: 3,
    prerequisites: ["Level 02 or Level 03"],
    skillsLearned: ["Position Sizing", "Correlation Matrices", "Rebalancing Schedules", "Drawdown Caps"],
    thumbnailUrl: "/courses/level-04.jpg",
    instructor: {
      name: "Siddharth Sen",
      title: "Technical Market Strategist",
      avatar: "SS",
    },
    modules: [],
  },
  {
    id: "course-5",
    slug: "advanced-hedging-derivatives",
    title: "Advanced Hedging & Market Volatility",
    level: "LEVEL 05",
    levelNumber: 5,
    category: "Derivatives",
    tagline: "Risk Protection without Speculation",
    description: "Understand India VIX, implied volatility distributions, and non-speculative equity portfolio hedging.",
    durationHours: 10,
    lessonsCount: 16,
    modulesCount: 4,
    prerequisites: ["Level 04: Portfolio Construction"],
    skillsLearned: ["India VIX Interpretation", "Protective Puts", "Covered Call Writing", "Risk-Neutral Spreads"],
    thumbnailUrl: "/courses/level-05.jpg",
    instructor: {
      name: "Aditya Verma",
      title: "Senior Market Educator",
      avatar: "AV",
    },
    modules: [],
  },
  {
    id: "course-6",
    slug: "professional-market-synthesis",
    title: "Professional Market Synthesis",
    level: "LEVEL 06",
    levelNumber: 6,
    category: "Institutional",
    tagline: "Institutional Macro & Comprehensive Equity Dossiers",
    description: "Synthesize macro interest rate cycles, FII/DII liquidity vectors, and machine learning research models.",
    durationHours: 12,
    lessonsCount: 18,
    modulesCount: 4,
    prerequisites: ["Completion of Levels 01–05"],
    skillsLearned: ["Macroeconomic Liquidity", "FII Flow Interpretation", "LSTM Probabilities", "Comprehensive Research"],
    thumbnailUrl: "/courses/level-06.jpg",
    instructor: {
      name: "Dr. Meera Nambiar",
      title: "Fundamental Equity Research Fellow",
      avatar: "MN",
    },
    modules: [],
  },
];

export const MOCK_ENROLLMENTS: DBEnrollment[] = [
  {
    id: "enr-1",
    userId: "demo_user",
    courseId: "course-2",
    progressPercent: 62,
    currentLessonId: "les-2-1-1",
    completedLessonIds: ["les-2-1-2"],
    isCompleted: false,
    enrolledAt: "2026-02-10T10:00:00Z",
  },
  {
    id: "enr-2",
    userId: "demo_user",
    courseId: "course-1",
    progressPercent: 100,
    currentLessonId: "les-1-1-2",
    completedLessonIds: ["les-1-1-1", "les-1-1-2", "les-1-2-1"],
    isCompleted: true,
    enrolledAt: "2026-01-05T09:00:00Z",
    completedAt: "2026-01-28T14:30:00Z",
  },
];

export const MOCK_CERTIFICATES: DBCertificate[] = [
  {
    id: "cert-1",
    userId: "demo_user",
    courseId: "course-1",
    courseTitle: "Level 01: Market Foundations & Structure",
    issuedAt: "January 28, 2026",
    verificationCode: "MH-2026-FND-8842",
    grade: "Honors",
  },
];

export const MOCK_WATCHLIST: DBWatchlistItem[] = [
  {
    id: "wl-1",
    userId: "demo_user",
    symbol: "RELIANCE",
    companyName: "Reliance Industries Ltd",
    sector: "Energy & Conglomerate",
    price: 3024.1,
    change: 25.5,
    changePercent: 0.85,
    sparkline: [2980, 2995, 3010, 3005, 3020, 3018, 3024],
    high52w: 3217.9,
    low52w: 2220.3,
    marketCapCr: 2045000,
    addedAt: "2026-02-14",
  },
  {
    id: "wl-2",
    userId: "demo_user",
    symbol: "TCS",
    companyName: "Tata Consultancy Services",
    sector: "Information Technology",
    price: 4192.5,
    change: 51.3,
    changePercent: 1.24,
    sparkline: [4120, 4140, 4135, 4170, 4185, 4192],
    high52w: 4592.25,
    low52w: 3313.0,
    marketCapCr: 1516000,
    addedAt: "2026-02-15",
  },
  {
    id: "wl-3",
    userId: "demo_user",
    symbol: "HDFCBANK",
    companyName: "HDFC Bank Ltd",
    sector: "Banking & Financials",
    price: 1684.2,
    change: 10.4,
    changePercent: 0.62,
    sparkline: [1660, 1672, 1668, 1675, 1680, 1684],
    high52w: 1794.0,
    low52w: 1363.55,
    marketCapCr: 1282000,
    addedAt: "2026-02-18",
  },
  {
    id: "wl-4",
    userId: "demo_user",
    symbol: "INFY",
    companyName: "Infosys Ltd",
    sector: "Information Technology",
    price: 1845.8,
    change: -5.9,
    changePercent: -0.32,
    sparkline: [1860, 1855, 1848, 1852, 1842, 1845],
    high52w: 1991.45,
    low52w: 1358.35,
    marketCapCr: 765000,
    addedAt: "2026-02-20",
  },
  {
    id: "wl-5",
    userId: "demo_user",
    symbol: "LT",
    companyName: "Larsen & Toubro",
    sector: "Capital Goods & Infra",
    price: 3620.0,
    change: 76.2,
    changePercent: 2.15,
    sparkline: [3510, 3530, 3560, 3580, 3605, 3620],
    high52w: 3919.9,
    low52w: 2860.0,
    marketCapCr: 497000,
    addedAt: "2026-02-22",
  },
];

export const MOCK_NOTIFICATIONS: DBNotification[] = [
  {
    id: "notif-1",
    userId: "demo_user",
    type: "LESSON_REMINDER",
    title: "Continue Your Learning Streak",
    message: "You are on day 7! Lesson 'Understanding Support & Resistance' is ready in Technical Analysis Foundations.",
    linkUrl: "/learn/courses/course-2/lesson/les-2-1-1",
    isRead: false,
    createdAt: "10 mins ago",
  },
  {
    id: "notif-2",
    userId: "demo_user",
    type: "COMMUNITY",
    title: "Saturday Market Breakdown",
    message: "This Saturday at 11:00 AM IST: Deconstructing Q3 Earnings & India VIX Volatility Compression.",
    linkUrl: "/community",
    isRead: false,
    createdAt: "2 hours ago",
  },
  {
    id: "notif-3",
    userId: "demo_user",
    type: "CERTIFICATE",
    title: "Certificate Issued",
    message: "Congratulations! Your verified certificate for Level 01: Market Foundations has been minted.",
    linkUrl: "/profile",
    isRead: true,
    createdAt: "3 days ago",
  },
  {
    id: "notif-4",
    userId: "demo_user",
    type: "SYSTEM",
    title: "Dhruvan LSTM Model Calibrated",
    message: "Historical backtest window updated with 1,250 trading sessions of NSE data.",
    linkUrl: "/ai-tools/dhruvan",
    isRead: true,
    createdAt: "5 days ago",
  },
];

export const MOCK_SUBSCRIPTION_PLANS: DBSubscriptionPlan[] = [
  {
    id: "plan-free",
    slug: "free",
    name: "Foundational Tier",
    priceMonthly: 0,
    priceAnnual: 0,
    currency: "INR",
    description: "Start understanding financial markets with foundational modules and basic screening.",
    features: [
      "Access to Level 01: Market Foundations",
      "Ruzhaa AI Tutor (20 concept queries / week)",
      "Standard Dhaleo Stock Screener (top 100 NSE stocks)",
      "Daily Market Overview & Ticker Feeds",
      "Determind Initial Risk Assessment",
    ],
    aiCreditsPerMonth: 80,
    coursesAccessible: "Level 01",
  },
  {
    id: "plan-pro",
    slug: "pro",
    name: "Investor Pro",
    priceMonthly: 1499,
    priceAnnual: 14390,
    currency: "INR",
    description: "For active learners and investors seeking in-depth equity research and advanced analysis.",
    features: [
      "Complete Access to Levels 01 through Level 04",
      "Unlimited Ruzhaa AI Financial Concept Tutor",
      "Full Dhaleo Screener across 2,400+ NSE/BSE equities",
      "Jaro Equity Analysis Terminal & dossiers",
      "Determind Full Behavioral & Emotional Risk Profiling",
      "Weekly Cohort Market Breakdown Webinars",
    ],
    aiCreditsPerMonth: "Unlimited",
    coursesAccessible: "Levels 01-04",
  },
  {
    id: "plan-premium",
    slug: "premium",
    name: "Institutional Alpha",
    priceMonthly: 3499,
    priceAnnual: 33590,
    currency: "INR",
    description: "Comprehensive ecosystem access including machine learning research models and direct mentor reviews.",
    features: [
      "Complete Access to All 6 Curriculum Levels",
      "All Pro features included",
      "Dhruvan AI LSTM Predictive Research Sandbox",
      "Direct 1-on-1 Monthly Mentor Research Review",
      "Custom Screener Formulas & Exportable Dossiers",
      "Priority Access to Masterclasses & Case Studies",
    ],
    aiCreditsPerMonth: "Unlimited",
    coursesAccessible: "All Levels",
  },
];
